server:
  port: 8080
spring:
  application:
    name: ppai
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://123.60.169.179:3306/ppai?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
      username: root
      password: root
mybatis:
  #config-location: classpath:mybatis/mybatis-config.xml # 指定mybatis-config.xml全局配置文件的位置，可以不写
  mapper-locations: mybatis/mapper/**/*.xml
  # 指定mapper.xml配置文件的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  # 开启下划线转驼峰命名

##配置文件上传路径
reggie:
  file: /shanyu/ruijiPhoto